import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const data = [
  {
    id: "1",
    img: "/ecoomerce.png",
    name: "Multivendor E-Commerce",
    description: [
      "User Login ,Register  and Logout,add to cart,add to wishlist,add Product review,buy product",
      "Show cart product with shop name,customer to seller real time chat ,User see cart ,wishlist,order,chat in your dashboard,Filter product with category, rating , price",
      "Search , pagination , show latest , related , highest price product with row and grid system.",
    ],
    useTecnology: [
      "Tailwind",
      "React Js",
      "Axios",
      "Redux toolkit",
      "stripe",
      "socket-io",
      "jwt",
      "cloudinary",
      "express",
      "mongoose",
      "formidable",
      "bcrypt",
      "react - apexChart",
      "spinners",
      "lazyload",
      "multi carousel",
      "hot-toast",
      "window",
      "range",
      "rating",
      "swiper",
      "moment",
      "and other",
    ],
    live: "https://multivendor-ecommerce-frontend.onrender.com/",
    code: "https://github.com/anishazahan/Multivendor-ecommerce-frontend",
    server: "https://github.com/anishazahan/multivendor-ecommerce-backend",
    type: "Fullstack",
  },

  {
    id: "2",
    img: "/quize.png",
    name: "Quiz App",
    description: [
      "Implement MVC architecture , Schema designs for questions and results, use Mongoose.",
      "If you don't enter your username, you will not be able to participate in the quiz,and show How many quizzes have you answered in total and your final achieved result.",
      "Use Custom hook, dynamic route, React Redux ,Load data dynamic way with loading.",
      "Use Tailwind. Beautiful UI design,Responsive for all devices.Clean code with necessary comments.",
    ],
    useTecnology: [
      "Tailwind",
      "Axios",
      "Redux",
      "Node Js",
      " Express Js",
      "Mongoose",
    ],
    live: "https://quiz-application.onrender.com/",
    code: "https://github.com/anishazahan/Quize-app",
    server: "https://github.com/anishazahan/Quiz-app-server",
    type: "Fullstack",
  },
  {
    id: "3",
    img: "/educart.png",
    name: "Edu-Cart (Learning & Earning Platform)",
    description: [
      "Instructor dashboard for creating and managing courses and modules",
      "Full CRUD operations on course modules (create, update, delete)",
      "Publish and unpublish control for courses and modules",
      "Unpublished content remains hidden from students",
      "View list of enrolled students and monitor course engagement",
      "Student dashboard to view and update personal profile",
      "Access enrolled courses and interact with published modules only",
    ],
    useTechnology: [
      "Next.js",
      "Tailwind CSS",
      "Shadcn UI",
      "Redux Toolkit",
      "Axios",
      "JWT Authentication",
      "Node.js",
      "MongoDB (Mongoose)",
      "Stripe Payment Gateway",
    ],
    live: "https://edu-cart.sankardevsishuvidyaniketanbihpuria.in/",
    code: "https://github.com/anishazahan/edu-cart",
    type: "Fullstack",
  },

  {
    id: "4",
    img: "/assestment.png",
    name: "Assessment Program",
    description: [
      "3-step progressive test flow (A1 → C2)",
      "Certification system (auto-generate based on score)",
      "Timer per test step with auto-submit on expiration",
      "Authentication & user management (JWT, OTP, forgot/reset password)",
      "Role-based access: Admin, Student, Supervisor",
      "Safe Exam Browser (SEB) integration for restricted exam environment",
      "Question pool with 132 categorized questions (22 competencies × 6 levels)",
      "Robust error handling, reusable components, pagination, and industry-standard code structure",
    ],
    useTechnology: [
      "Next.js (TypeScript)",
      "Redux Toolkit",
      "RTK Query",
      "Axios",
      "Tailwind CSS",
      "Redux Persist",
      "Node.js (TypeScript)",
      "Express.js",
      "MongoDB (Mongoose)",
      "JWT",
      "Nodemailer",
      "Twilio",
    ],
    live: "https://test-assessment-program.netlify.app/",
    code: "https://github.com/anishazahan/School-assesment-competency-platform-FE",
    server: "https://github.com/anishazahan/Test-School-competency-platform-BE",
    type: "Fullstack",
  },
  {
    id: "5",
    img: "/user-dashboard.png",
    name: "User Dashboard",
    description: [
      "User management system with real-time search by name, email, or username",
      "Smart pagination with customizable page sizes",
      "Comprehensive user profiles including company and address details",
      "Smooth navigation between user list and detailed views",

      "Advanced animations using Framer Motion across the application",
      "3D card transforms with realistic depth effects",
      "Floating geometric elements responding to mouse movement",
      "Particle-based animated background system",
      "Interactive hover effects, micro-interactions, and animated counters",
      "Smooth loading and transition animations",

      "Mobile-first responsive design with collapsible navigation",
      "Skeleton loading states and graceful error boundaries",
      "Professional typography, spacing, and layout polish",
      "Performance-optimized UI across all device sizes",

      "SEO-optimized metadata and structured pages",
      "Accessibility-focused implementation",
      "Clean, maintainable, and scalable code architecture",
      "Professional error handling and smooth page transitions",
    ],
    useTechnology: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Shadcn UI",
      "Lucide Icons",
    ],
    live: "https://jazzy-mousse-4ca938.netlify.app/",
    code: "https://github.com/anishazahan/user-dashboard",
    type: "Fullstack",
  },
  {
    id: "6",
    img: "/sales.png",
    name: "Sales Dashboard",
    description: [
      "Date range filtering with instant application using start and end dates",
      "Advanced filters including minimum price, customer email, and phone number search",
      "Time-series line chart displaying total sales aggregated by day",
      "Data visualization built using Recharts",
      "Sortable data table with ascending and descending indicators on date and price columns",
      "Displays up to 50 records per page for efficient browsing",
      "Cursor-based pagination using API tokens for high-performance data fetching",
      "Previous and next navigation with proper state management and no page reset issues",
      "Smart caching using SWR with request deduplication and one-minute cache duration",
      "Instant navigation to previously visited pages without refetching",
      "Offline support using cached data and no refetch on browser tab focus",
      "Fully responsive layout optimized for desktop, tablet, and mobile devices",
      "Mobile-optimized UI with stacked filters and smooth table scrolling on small screens",
    ],
    useTechnology: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn UI",
      "Framer Motion",
      "Lucide Icons",
      "Redux Toolkit",
      "RTK Query",
      "Node.js",
      "Express.js",
      "MongoDB (Mongoose)",
      "Recharts",
    ],
    live: "https://anisha-sales-dashboard.netlify.app/",
    code: "https://github.com/anishazahan/Sales-Dashboard-FE",
    type: "Fullstack",
  },

  {
    id: "13",
    img: "/heading-widject.png",
    name: "Headline Widget",
    description: [
      "Editable headline text with real-time preview",
      "Comprehensive typography controls including font size, family, weight, alignment, letter spacing, and line height",
      "Gradient text support with directional controls and multiple color pickers",
      "Collapsible configuration sections for a clean and professional UI",

      "Word and segment-level styling such as highlight, underline, background color, bold, and italic",
      "Advanced text animations including fade-in, slide-up, bounce, glow, shimmer, and typewriter effects",
      "Additional text effects such as shadows, outlines, and custom positioning",
      "Export options for JSON configuration, CSS styles, HTML snippets, and React components",

      "Dark and light mode with system preference detection",
      "Fully responsive design across desktop, tablet, and mobile devices",
      "State persistence using localStorage for saving and loading configurations",
      "Live character and word count statistics",
      "Polished UI animations implemented with Framer Motion",

      "Strictly typed implementation using TypeScript",
      "Built with React 18 using hooks and custom hooks",
      "Tailwind CSS 3 with custom animation utilities",
      "Accessibility-focused implementation with ARIA labels and keyboard navigation",
      "Performance-optimized architecture with clean state management",
    ],
    useTechnology: [
      "React 18",
      "TypeScript",
      "Tailwind CSS 3",
      "Framer Motion",
      "LocalStorage API",
      "Vite",
    ],
    live: "https://heading-widget-anisha.netlify.app/",
    code: "https://github.com/anishazahan/heading-widjet",
    server: "",
    type: "Frontend",
  },

  {
    id: "7",
    img: "/creative.png",
    name: "Creative Agency",
    description: [
      "Using Tailwind, Next Js for good performance optimization and advance animation used",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Axios",
      "Redux",
      "Framer Motion",
      "GSAP",
      "Shadcn UI",
    ],
    live: "https://anisha-creative-agency.netlify.app/",
    code: "https://github.com/anishazahan/Anisha-Creative-Agency-Framer-motion-GSAP-",
    type: "Frontend",
  },
  {
    id: "8",
    img: "/portfolio.png",
    name: "Portfolio Landing",
    description: [
      "Using Tailwind, Next Js for good performance optimization and advance animation used",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Axios",
      "Redux",
      "Framer Motion",
      "GSAP",
      "Shadcn UI",
    ],
    live: "https://anisha-zahan.sankardevsishuvidyaniketanbihpuria.in/",
    code: "https://github.com/anishazahan/next-potfolio",
    type: "Frontend",
  },
  {
    id: "9",
    img: "/positivious.png",
    name: "Positivious Landing",
    description: [
      "Using Tailwind, Next Js for good performance optimization and advance animation used",
      "Light Dark mood features",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Axios",
      "Redux",
      "Framer Motion",
      "GSAP",
      "Shadcn UI",
    ],
    live: "https://positivus-anihsha.netlify.app/",
    code: "https://github.com/anishazahan/Positivus",
    type: "Frontend",
  },
  {
    id: "10",
    img: "/cloude.png",
    name: "My Cloude",
    description: [
      "Using Tailwind, Next Js for good performance optimization and advance animation used",
      "Light Dark mood features",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Axios",
      "Redux",
      "Framer Motion",
      "GSAP",
      "Shadcn UI",
    ],
    live: "https://silly-concha-c6b06c.netlify.app/",
    type: "Frontend",
  },
  {
    id: "11",
    img: "/last.png",
    name: "PPM Landing",
    description: [
      "Using Tailwind, Next Js for good performance optimization and advance animation used",
      "Light Dark mood features",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Axios",
      "Redux",
      "Framer Motion",
      "GSAP",
      "Shadcn UI",
    ],
    live: "https://lovely-frangipane-d90864.netlify.app/",
    type: "Frontend",
  },

  {
    id: "12",
    img: "/chat-health.png",
    name: "Chat-health Dashboard",
    description: [
      "Using Tailwind, Next Js for good performance optimization",
      "Cross browser operability,Responsive design for all devices.",
      "Process improvement,workflow optimization.User Requirement Gathering.",
      "Fresh,Comentable,CleanCode,Error handling, Debugging,fixing problems.Client Interaction this project.",
    ],
    useTecnology: [
      "Tailwind",
      "Next Js",
      "Aos animation",
      "Swiper slide",
      "Framer Motion",
    ],
    live: "https://gleaming-brioche-35bca7.netlify.app/",
    code: "https://github.com/anishazahan/chat-health",
    server: "",
    type: "Frontend",
  },
];
